name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - v*

jobs:
  test_backend:
    runs-on: ubuntu-latest
    name: Install Dependency & Test - Backend
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Setup and run tests
        working-directory: .
        run: |
          rm -rf node-modules
          export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
          yarn
          yarn test